### ISSUE TITLE
The weather dataset could be further specified

### ISSUE THREAD

**Issue by cmcuza** [TatsuyaD7/Time-Series-Work-Conference#6]
Hi, 

Thank you for the great work. 

This is more of a suggestion than an issue. 

Different papers use different weather datasets. So far I have found two: one is from USA weather stations with one-hour aggregation and the other is from Max Plank institute with 10 mins aggregation. Moreover, it looks like different authors are using the Max Plank dataset differently. For example, some of them are using 2 years of data while others are only using one. 

I thought about bringing this up in case you want to bring this level of detail. If you want I could help :) 

Best.

**Comment by lixus7** [comment]
Hi,

Sorry for the late reply! It's my fault that the dataset description is not clear. The same problem also occurs on other datasets such as the NYC dataset. I think I'll do something to separate them later when I have more free time in the future. I even want to arrange a separate page for all the details of the datasets to show.

As for the errors about the weather dataset, you can push your version if you want. I will be very grateful for your help because your understanding of this dataset will be more correct!
